version: '3.8'
services:
  mongodb:
    image: mongo:5.0.15
    container_name: tien-mongodb-4rn-mongodb-1
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

    # docker compose -p tien-mongodb-4rn up -d
